# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 08:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('fecha_orden', models.DateField()),
                ('edad', models.IntegerField()),
                ('direccion', models.CharField(max_length=100)),
                ('nit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('tipoproducto', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=30)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Menu')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='clientes',
            field=models.ManyToManyField(through='clientes.Orden', to='clientes.Menu'),
        ),
    ]
